## Create a new block
POST http://localhost:3000/api/pages/1/blocks HTTP/1.1
content-type: application/json

{
    "type": "image",
    "content": "turin.jpg",
    "position": 4
}
###

## Get block
GET http://localhost:3000/api/pages/3/blocks/6 HTTP/1.1
###

## Get block (expect error)
GET http://localhost:3000/api/pages/3/blocks/1 HTTP/1.1
###


## Update a block
PUT  http://localhost:3000/api/pages/1/blocks/14 HTTP/1.1
content-type: application/json

{
    "type": "image",
    "content": "dog.jpg",
    "position": 5
}
###