## Create a new page
POST http://localhost:3000/api/pages HTTP/1.1
content-type: application/json

{
    "title": "test page to delete"
}
###

## Get all pages
GET http://localhost:3000/api/pages HTTP/1.1
###

## Get all published pages
GET http://localhost:3000/api/pages/published HTTP/1.1
###

## Get all pages by the user logged in
GET http://localhost:3000/api/authors/admin/pages HTTP/1.1
###

## Get a specific page
GET http://localhost:3000/api/pages/1 HTTP/1.1
###

## Get a specific page (expect 404)
GET http://localhost:3000/api/pages/0 HTTP/1.1
###

## Get a published page
GET http://localhost:3000/api/pages/published/3 HTTP/1.1
###

## Get a published page (expect error)
GET http://localhost:3000/api/pages/published/5 HTTP/1.1
###

## Update an existing page (admin only)
PUT http://localhost:3000/api/pages/1 HTTP/1.1
content-type: application/json

{
    "title": "test page updated",
    "author": "admin",
    "publicationDate": "2023-06-04"
}
###

## Delete an existing page (admin only)
DELETE http://localhost:3000/api/pages/13 HTTP/1.1
###

## Update an existing page (author only)
PUT http://localhost:3000/api/authors/admin/pages/1 HTTP/1.1
content-type: application/json

{
    "title": "Lorem ipsum dolor sit",
    "author": "admin",
    "publicationDate": "2023-06-12"
}
###

## Delete an existing page (author only)
DELETE http://localhost:3000/api/pages/13 HTTP/1.1
###